language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libboost1.54-dev
script:
  - export CTEST_OUTPUT_ON_FAILURE=1
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=debug ..
  - make
  - make test
notifications:
  slack:
    rooms:
      secure: KEIM0ixZgLO+JpA+GEf3JKEchEaf+zf2qzPl0X4U6dPA1T/vrRHFIrn5vG4Bdyc/W/wFGdqVt2S/Ljgnhrqy/TpeZTg9DGRlVVRZylkAZYDmRS8R3b7wjKsMg0vaAI4vCoD3mr9aY1IyI+d5KanFM68mSZc0jgbuuFgwtLVHdowAyowQnWhGiw88JacdM0+EFgDZ/qnNU5eCRhh7KDf0BxDX7Rm1CzjEUevI6D+3ESnF50TQX7mfSq8qv02J30pHTmIN7hh/9FglC4t7MVMmKrBxIphh7dy3mN9YBXlNYs3DBxZ+gNu20RtwWMw6pIRVsThED8pyRDX5WJ0all+YJ2+n2r+PGLFRtBTa2Gj1au78Q7QHQzltzLru/dp2NM7zOS9R2x5WAay8Z/E2LOMzFrlt/ObTRtEozMtNvIC19kotDYwwvPaogEIlIB0/ahZ+1pWGthVqwz5OOB8FgUHHaRlBL3cmQfnSDJGYol1Ut/6paBtfB+r0tYSNWZak6FI2tnP708R1UvsWMhUu8BSiYkeTLz86qnSoD4MXIlAacTFdZOYpL4Q08OpmW70GFpOTmTNtAPkTlVuyzw3iY837chKyB9ToyeE6uBwG4AhMwfTz8wViBJZ20BsjY2sWnReJgOa8HEhTWZSiqLu6ZX7FHWNSzIZ78sXrN6VuVI5CdL8=
