language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
script:
  - export CTEST_OUTPUT_ON_FAILURE=1
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=debug ..
  - make
  - make test
